//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet
    {
        public pet()
        {
            this.carts = new HashSet<cart>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public double weight { get; set; }
        public string type { get; set; }
        public string color { get; set; }
        public string origin { get; set; }
        public double price { get; set; }
        public string imageslink { get; set; }
        public double pricebefore { get; set; }
        public string checkquality { get; set; }
        public string description { get; set; }
        public int rate { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<cart> carts { get; set; }
    }
}
