//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetsProject.Resources.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address book.
        /// </summary>
        public static string AddressBook {
            get {
                return ResourceManager.GetString("AddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamlet 6, Linh Trung Ward, Thu Duc District, Ho Chi Minh City, Vietnam.
        /// </summary>
        public static string AddressStore {
            get {
                return ResourceManager.GetString("AddressStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string AddtoCard {
            get {
                return ResourceManager.GetString("AddtoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart Success!.
        /// </summary>
        public static string AddToCartSuccess {
            get {
                return ResourceManager.GetString("AddToCartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at now.
        /// </summary>
        public static string AtNow {
            get {
                return ResourceManager.GetString("AtNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availibility.
        /// </summary>
        public static string Availibility {
            get {
                return ResourceManager.GetString("Availibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic infomation.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Categories.
        /// </summary>
        public static string BrowseCategories {
            get {
                return ResourceManager.GetString("BrowseCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I want to buy more items.
        /// </summary>
        public static string BuyMoreItem {
            get {
                return ResourceManager.GetString("BuyMoreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy now.
        /// </summary>
        public static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled bill.
        /// </summary>
        public static string CancelledBill {
            get {
                return ResourceManager.GetString("CancelledBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string CardProduct {
            get {
                return ResourceManager.GetString("CardProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check quality.
        /// </summary>
        public static string CheckQuality {
            get {
                return ResourceManager.GetString("CheckQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your available address.
        /// </summary>
        public static string ChooseAvailableAddress {
            get {
                return ResourceManager.GetString("ChooseAvailableAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment:.
        /// </summary>
        public static string ChoosePayment {
            get {
                return ResourceManager.GetString("ChoosePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPass {
            get {
                return ResourceManager.GetString("ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Shipping on all order.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t hesitate to tell me if you have any problems!.
        /// </summary>
        public static string ContentFooter {
            get {
                return ResourceManager.GetString("ContentFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our website specializes in providing quality pets at reasonable prices. Hurry up to order to get more offers..
        /// </summary>
        public static string ContentSliderIndex {
            get {
                return ResourceManager.GetString("ContentSliderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueShopping.
        /// </summary>
        public static string ContinueShopping {
            get {
                return ResourceManager.GetString("ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered bill.
        /// </summary>
        public static string DeliveredBill {
            get {
                return ResourceManager.GetString("DeliveredBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart is empty!.
        /// </summary>
        public static string EmptyCart {
            get {
                return ResourceManager.GetString("EmptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashon Category.
        /// </summary>
        public static string FashonCategory {
            get {
                return ResourceManager.GetString("FashonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Shipping.
        /// </summary>
        public static string FreeShipping {
            get {
                return ResourceManager.GetString("FreeShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name:.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to shop.
        /// </summary>
        public static string GoBackToShop {
            get {
                return ResourceManager.GetString("GoBackToShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have error.
        /// </summary>
        public static string HaveError {
            get {
                return ResourceManager.GetString("HaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string ManageYourAccount {
            get {
                return ResourceManager.GetString("ManageYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufactory.
        /// </summary>
        public static string Manufactory {
            get {
                return ResourceManager.GetString("Manufactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPass {
            get {
                return ResourceManager.GetString("OldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On way bill.
        /// </summary>
        public static string OnWayBill {
            get {
                return ResourceManager.GetString("OnWayBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID:.
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order info.
        /// </summary>
        public static string OrderInfo {
            get {
                return ResourceManager.GetString("OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER NOW.
        /// </summary>
        public static string OrderNow {
            get {
                return ResourceManager.GetString("OrderNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been received.
        /// </summary>
        public static string OrderReceived {
            get {
                return ResourceManager.GetString("OrderReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment available.
        /// </summary>
        public static string PaymentAvailable {
            get {
                return ResourceManager.GetString("PaymentAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method:.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent address:.
        /// </summary>
        public static string PermanentAddress {
            get {
                return ResourceManager.GetString("PermanentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product detail page.
        /// </summary>
        public static string ProductDetail {
            get {
                return ResourceManager.GetString("ProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Filters.
        /// </summary>
        public static string ProductFilters {
            get {
                return ResourceManager.GetString("ProductFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PURCHASE INFO.
        /// </summary>
        public static string PurchaseInfo {
            get {
                return ResourceManager.GetString("PurchaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received bill.
        /// </summary>
        public static string ReceivedBill {
            get {
                return ResourceManager.GetString("ReceivedBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment will be redirect to PayPal Sandbox.
        /// </summary>
        public static string RedirectToPayPal {
            get {
                return ResourceManager.GetString("RedirectToPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Product.
        /// </summary>
        public static string SampleProduct {
            get {
                return ResourceManager.GetString("SampleProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save my avatar.
        /// </summary>
        public static string SaveMyAvatar {
            get {
                return ResourceManager.GetString("SaveMyAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default.
        /// </summary>
        public static string SetDefault {
            get {
                return ResourceManager.GetString("SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Category page.
        /// </summary>
        public static string ShopCategoryPage {
            get {
                return ResourceManager.GetString("ShopCategoryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        public static string ShoppingCartTitle {
            get {
                return ResourceManager.GetString("ShoppingCartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signin infomation.
        /// </summary>
        public static string SigninInfo {
            get {
                return ResourceManager.GetString("SigninInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7 Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We believe you will be very satisfied with our sample products below.
        /// </summary>
        public static string TextSampleProduct1 {
            get {
                return ResourceManager.GetString("TextSampleProduct1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please trust our shop.
        /// </summary>
        public static string TextSampleProduct2 {
            get {
                return ResourceManager.GetString("TextSampleProduct2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total to pay:.
        /// </summary>
        public static string TotalToPay {
            get {
                return ResourceManager.GetString("TotalToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted product.
        /// </summary>
        public static string TrustedProduct {
            get {
                return ResourceManager.GetString("TrustedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have all.
        /// </summary>
        public static string YouHaveAll {
            get {
                return ResourceManager.GetString("YouHaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no bill at this time.
        /// </summary>
        public static string YouNoBill {
            get {
                return ResourceManager.GetString("YouNoBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your address.
        /// </summary>
        public static string YourAddress {
            get {
                return ResourceManager.GetString("YourAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Avatar.
        /// </summary>
        public static string YourAvatar {
            get {
                return ResourceManager.GetString("YourAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Order.
        /// </summary>
        public static string YourOrder {
            get {
                return ResourceManager.GetString("YourOrder", resourceCulture);
            }
        }
    }
}
